# Generated by Django 5.1.3 on 2025-05-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TutorProfile',
        ),
    ]
